spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id : product-service
          uri : ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/product-service/**

        - id : user-service
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/user-service/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/order-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
